### ISSUE TITLE
Dynamic crypto backend

### ISSUE THREAD

**Issue by thomcc** [mozilla/rust-ece#35] opened 2019-07-11 03:49 UTC
While I'm not opposed to putting the crypto code in appservices onto crates.io, Ed we'd have to do that before OpenSSL in this crate (and thus in in a-s) could be removed, as this crate can't easily be changed to work in the same way `hawk` was changed in https://github.com/taskcluster/rust-hawk/pull/23.

I said I'd take a look, and I think this would work:

```rust
pub trait Crypto {
    fn generate_ephemeral_keypair(&self) -> Result<Box<dyn LocalKeyPair>>;
    fn compute_ecdh_secret(
        &self,
        remote: &dyn RemotePublicKey,
        local: &dyn LocalKeyPair,
    ) -> Result<Vec<u8>>;
    fn hkdf_sha256(&self, salt: &[u8], secret: &[u8], info: &[u8], len: usize) -> Result<Vec<u8>>;
    /// Should return [ciphertext, auth_tag].
    fn aes_gcm_128_encrypt(&self, key: &[u8], iv: &[u8], data: &[u8], tag_len: usize) -> Result<Vec<u8>>;
    fn aes_gcm_128_decrypt(&self, key: &[u8], iv: &[u8], data: &[u8], tag: &[u8]) -> Result<Vec<u8>>;
    fn random(&self, dest: &mut [u8]) -> Result<()>;

    // replaces LocalKeyPair::generate_random
    fn random_local_key_pair(&self) -> Box<dyn LocalKeyPair>;
    // replaces LocalKeyPair::from_raw_components
    fn local_key_pair_from_raw_components(&self, components: &EcKeyComponents) -> Box<dyn LocalKeyPair>;
    // replaces LocalKeyPair::from_raw
    fn remote_public_key_from_raw(&self, bytes: &[u8]) -> Box<dyn RemotePublicKey>;
}


pub trait RemotePublicKey {
    /// Export the key component in the
    /// binary uncompressed point representation.
    fn as_raw(&self) -> Result<Vec<u8>>;
}

pub trait LocalKeyPair {
    /// Export the public key component in the
    /// binary uncompressed point representation.
    fn pub_as_raw(&self) -> Result<Vec<u8>>;
    /// Export the raw components of the keypair.
    fn raw_components(&self) -> Result<(EcKeyComponents)>;
}
```

You'd then have code to configure the global `Crypto` impl the same way the `hawk` crate does with it's `Cryptographer` object.   Note that I'm not sure if I missed anything in the backend API, but hopefully this at least gives you the gist of how you'd redesign it

This might require a little bit of downcasting, in practice I don't expect it to be that bad. You'd lose the static guarantee that someone doesn't do something like create a `Box<dyn LocalKeyPair>` with e.g. a OpenSSL-backed `Crypto` and then pass it into NSS or Ring-backed one, but this seems fascinatingly unlikely to me, and like you could just `unwrap()` the result of your downcasting without sweating it (To be clear, you'd still be certain of this, it would just be a runtime check, and not one you can forget to make).

And so it's mostly an ergonomic (and slight performance\*) loss, and I suspect that the ergonomics loss would be entirely internal and trait objects/etc would be hidden from most of the public API, outside of the case for replacing the backend.

To be clear I don't know that you should do this over just publishing rc_crypto and using it here, but I don't think it would be particularly hard.

CC @eoger, @rfk 

---

\*: In practice these dynamic calls mostly devirtualize since there's only one implementation of the traits per program, but you still have some extra Box-ing.

**Comment by rfk** [comment] 2019-09-02 04:36
We did this in https://github.com/mozilla/rust-ece/commit/d24ab10f778294442606beb859fa2c294842adf7, closing.

**Closed as completed by rfk** 2019-09-02 04:36 UTC

**Comment by tiesselune** [comment] 2021-01-17 22:01
Sorry to revive this old issue, but I have a problem that is closely related to it.

Either there is something that I really don't get or there's something amiss.

Basically I've been trying to use `AesGcmEceWebPush` and more precisely its `encrypt` method.

The documentation states that it needs an implementor of the `RemotePublicKey` trait as its public key. Which is then downcasted to an `OpenSSLRemotePublicKey` somewhere during the encryption process. And this type is not made available... So I can pass the function any implementor of this trait, which has to be my own since the main one is unaccessible, but it's gonna be downcasted to an entirely different type, which will always fail. (Currently, calling `encrypt` panics in `openssl.rs`, trying to downcast my key to `OpenSSLRemotePublicKey`)

I saw that there was a `import_public_key` method in the `Cryptographer` trait, but aside from the trait, the actual implementation is not accessible either, which makes it impossible to call the function.

I'm guessing that there must be a way to use this encrypt function, but I really don't see how, aside from re-coding the entire crypto module... But it must be in there for a reason... Is there something I'm not seeing?

Thanks in advance!

**Comment by rfk** [comment] 2021-01-25 04:44
@tiesselune any chance you can post a bit of sample code that shows the error you're getting?

> I can pass the function any implementor of this trait, which has to be my own since the main one is unaccessible,
> but it's gonna be downcasted to an entirely different type

If I'm understanding correctly, I think you need to arrange for the global `Cryptographer` backend to be initialized with an instance of whatever backend you're trying to use, via one of the functions [here](https://github.com/mozilla/rust-ece/blob/64af2968ebaab43b5a2206795ad64de3153e585f/src/crypto/holder.rs#L19). The three traits `Cryptographer`, `RemotePublicKey` and `LocalKeyPair` all need to be implemented together to make a working backend, similar to what's done in the default [`openssl` backend](https://github.com/mozilla/rust-ece/blob/master/src/crypto/openssl.rs) or in this one [based on NSS](https://github.com/mozilla/application-services/blob/3fc42b212b12493e4113ed787cfa985b0b269a24/components/support/rc_crypto/src/ece_crypto.rs).

You can't just use your own `RemotePublicKey` impl in conjunction with a the openssl (or any other) backend.

> I'm guessing that there must be a way to use this encrypt function, but I really don't see how, aside from
> re-coding the entire crypto module

Which I think is what you're getting at here about "re-coding the entire crypto module".

Internally, we would call this function by using `crypto::holder::get_crypotographer` and then calling its trait methods to obtain an appropriate key, similar to what's done [here](https://github.com/mozilla/rust-ece/blob/64af2968ebaab43b5a2206795ad64de3153e585f/src/lib.rs#L37) for `Aes128GcmEceWebPush::encrypt`. But as you note, `get_cryptographer` is not available outside of the crate.

So, I think you're right that there's no way to actually call this method from outside of the crate. This method should not be marked `pub` in its current form.

> Basically I've been trying to use AesGcmEceWebPush and more precisely its encrypt method.

Without knowing your use-case...are you sure you want to call this method? It's based on a legacy draft spec and IIRC it has some rough edges that are much improved in the newer `Aes128GcmWebPush::encrypt` method, which you *can* call publicly via the top-level function linked above.

If you do need access to this method, I think I'd support a PR that makes `get_cryptographer` public so that you can access the currently-configured backend. Or perhaps a top-level helper function named something like `encrypt_legacy_aesgcm` to make it available in an easy-to-call fashion (but without encouraging consumers to use the legacy format it entails).

**Comment by tiesselune** [comment] 2021-01-28 23:39
Thanks for your answer!

> @tiesselune any chance you can post a bit of sample code that shows the error you're getting?

Well I'm not getting an *error* per se, I'm just trying to use [functions that are public and use trait arguments](https://github.com/mozilla/rust-ece/blob/64af2968ebaab43b5a2206795ad64de3153e585f/src/aesgcm.rs#L95) that I can't provide since the implementors are not made public. In the case of the OpenSSL backend there is even [this downcast](https://github.com/mozilla/rust-ece/blob/64af2968ebaab43b5a2206795ad64de3153e585f/src/crypto/openssl.rs#L153) that proved to me that I couldn't just implement the trait on my own structure since it was going to be downcasted into a type that I don't have any access to... So the way I saw it was: if you want to use this function, you need to re-code an entire backend since you won't be able to provide it with the right `RemotePublicKey` implementor. I tried generating keys by getting access to the underlying `Cryptographer` but it's private as well.

> Without knowing your use-case...are you sure you want to call this method? It's based on a legacy draft spec and IIRC it has some rough edges that are much improved in the newer Aes128GcmWebPush::encrypt method, which you can call publicly via the top-level function linked above.

Well, I was working on updating the [`rust-web-push` crate](https://github.com/pimeys/rust-web-push) that is unmaintained and lacks support for Aes128gcm. But since it was supposed to support both encodings, I tried to start by using the `rust-ece` to replace the custom AesGcm implementation in the crate for consistency purposes (and to get back to a KISS approach : let the `rust-ece` crate handle the ece work an focus on the actual notification process). Which proved to be rather difficult due to my comment above.

So personally I don't mind dropping support for AesGcm, since all current push services implement the newer Aes128Gcm, but I did not want to make a PR to the `rust-web-push` crate that removed a feature since it would be a major breaking change and would have preferred updating it to use the `rust-ece` functionality for both encodings since `rust-ece` seemed to be supporting both.

So if I understand correctly there's no way of using the AesGcm encoding scheme, and the "normal" way to use the crate is to use the top level functions in lib.rs that use Aes128Gcm by default ? But in that case how would you use the AesGcm version? Is the code considered obsolete and is it meant to be removed entirely in the future ?

**Comment by rfk** [comment] 2021-01-29 01:15
> Well, I was working on updating the rust-web-push crate that is unmaintained and lacks support for Aes128gcm

Aha, yes, that's a very valid use-case for calling this method.

> So if I understand correctly there's no way of using the AesGcm encoding scheme, and the "normal" way to use the crate
> is to use the top level functions in lib.rs that use Aes128Gcm by default?

Yes, that's the intended "normal" way to use this crate, and I think it would be reasonable to add AesGcm versions of these functions to support that.

> But in that case how would you use the AesGcm version?

In the place where we use this in production right now ([here](https://github.com/mozilla/application-services/blob/main/components/push/src/crypto.rs)) it turns out that we we did what you specifically want to avoid, and we re-implemented all the crypto-backend traits. That's probably why we didn't notice the fact that you can't call it without doing so :-(

You've convinced me this is a bug in the public API of this crate, and we should fix it *somehow*. Options include:

* Adding `get_cryptographer` to our public API surface [here](https://github.com/mozilla/rust-ece/blob/64af2968ebaab43b5a2206795ad64de3153e585f/src/crypto/mod.rs#L13), allowing consumers to access its `import_*` methods to create objects of the correct type. Easy to implement, but puts more complexity on the consumer.
* Adding top-level `encrypt_legacy_aesgcm` and `decrypt_legacy_aesgcm` functions to the crate. Much simpler for consumers, but more fiddly to implement.

Would you be willing to put up a PR taking either of those approaches? I would be happy to review.

Longer term, we should take a more holistic look at what's public in the API of this crate and whether we actually intend it to be.

> Is the code considered obsolete and is it meant to be removed entirely in the future ?

No, I expect we'll keep it indefinitely.

**Comment by tiesselune** [comment] 2021-01-29 23:10
>  That's probably why we didn't notice the fact that you can't call it without doing so

So I was not crazy after all! 😅 I've spent quite some time trying to figure out the way it was intended to work. 

> You've convinced me this is a bug in the public API of this crate, and we should fix it somehow.

The second approach seems more appropriate, probably? Shouldn't we be adding documentation hints on the public interfaces that are not really meant to be used without extra work, as we're at it ?

> Would you be willing to put up a PR taking either of those approaches?

Well I think I could *try*, at least, I'm not a crypto expert so I hope I won't run into implementation-specific trouble, but there's a first time to everything and I like a challenge. If it's mainly providing new interfaces to existing functions, I think I'll be alright.

How would you feel about having a public `legacy` module at top level with `encrypt_aesgcm` and `decrypt_aesgcm` functions instead (to avoid legacy clutter at top level)?

EDIT: I've started a pull request (#47); in order to finish it I'd need test data but I'm not sure where to get any (I just used the IETF example data from the draft for now). How did you generate the non-IETF data for the tests in the main lib ?

**Comment by rfk** [comment] 2021-01-31 23:11
> The second approach seems more appropriate, probably?

Yes, that sounds right.

> Shouldn't we be adding documentation hints on the public interfaces that are not really meant
> to be used without extra work, as we're at it?

We should indeed.

> Well I think I could try, at least, I'm not a crypto expert so I hope I won't run into implementation-specific trouble,
> but there's a first time to everything and I like a challenge. If it's mainly providing new interfaces to existing functions,
> I think I'll be alright.

Right, I'm hopeful that all the crypto bits will be taken care of by the existing code, and the new functions can stitch them together for the comment usecase.

> How would you feel about having a public legacy module at top level with encrypt_aesgcm and decrypt_aesgcm
> functions instead (to avoid legacy clutter at top level)?

I like this a lot, thanks for suggesting it!
